version: 2
jobs:
  one:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  two:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 3

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
