version: 2
jobs:
  one:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A first hello"
      - run: npm i gulp
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          path: ~/node_modules
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
        # Must be an absolute path, or relative path from working directory
          root: my_workspace
          paths:
            - echo-output
  two:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: echo "A more familiar hi"
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo ":("; exit 1
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
